os: linux
sudo: required
language:
- minimal
services:
- docker

jobs:
  include:
    - name: "checks"
      script:
      - docker run  -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap:cpp scripts/checks.sh
      - chmod 777 ./cpplint.py
      - ( for file in $(find ./ -name "*.cpp"); do ./cpplint.py $file || exit; done$
    - name: "tests"
      script:
      - ./scripts/genenv.sh
      - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap:cpp scripts/tests.sh

notifications:
    email: false
